```sql
-- ============================================================================
-- Migration: 005_create_appointments_schema.sql
-- Description: Appointments and appointment reminders tables for HMS
-- HIPAA Notice: Appointment data constitutes PHI (Protected Health Information).
--               Access must be role-based, logged, and encrypted at rest.
--               Retention policies must comply with applicable HIPAA guidelines.
-- Dependencies: 001_create_base_schema.sql (clinics)
--               003_create_users_staff_schema.sql (users)
--               004_create_doctors_schema.sql (doctors)
--               patients table (assumed created or to be created)
-- Author: HMS Database Architect
-- Created: 2025
-- ============================================================================

-- ----------------------------------------------------------------------------
-- ENUM TYPES
-- Using PostgreSQL native enums for type-safety and query performance.
-- Enums are immutable without ALTER TYPE; extend carefully in future migrations.
-- ----------------------------------------------------------------------------

-- Appointment lifecycle status
-- HIPAA: Status transitions may reveal sensitive scheduling PHI; audit all changes.
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'appointment_status') THEN
        CREATE TYPE appointment_status AS ENUM (
            'scheduled',   -- Initial state: booked but not yet confirmed
            'confirmed',   -- Confirmed by staff or automated system
            'completed',   -- Visit concluded successfully
            'cancelled',   -- Explicitly cancelled by patient, doctor, or staff
            'no_show'      -- Patient did not arrive; billable in some jurisdictions
        );
    END IF;
END $$;

-- Appointment modality type
-- HIPAA: Telehealth ('online') sessions require additional BAA and platform compliance.
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'appointment_type') THEN
        CREATE TYPE appointment_type AS ENUM (
            'in_person',   -- Physical clinic visit
            'online'       -- Telehealth / video consultation
        );
    END IF;
END $$;

-- Reminder delivery channel type
-- HIPAA: Each channel (SMS, email, WhatsApp) requires patient consent before use.
--        Reminder content must NOT include diagnosis or treatment details.
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'reminder_type') THEN
        CREATE TYPE reminder_type AS ENUM (
            'sms',         -- SMS via PSTN carrier; lowest fidelity, widely supported
            'email',       -- Email; must be sent over TLS; avoid PHI in subject line
            'whatsapp'     -- WhatsApp Business API; requires end-to-end encryption verification
        );
    END IF;
END $$;

-- Reminder delivery status
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'reminder_status') THEN
        CREATE TYPE reminder_status AS ENUM (
            'pending',     -- Queued, not yet dispatched
            'sent',        -- Dispatched to delivery provider
            'delivered',   -- Confirmed delivery receipt from provider
            'failed',      -- Delivery failed; may retry depending on policy
            'cancelled'    -- Reminder voided (e.g., appointment cancelled before send)
        );
    END IF;
END $$;

-- ----------------------------------------------------------------------------
-- TABLE: appointments
-- Core scheduling entity linking patients, doctors, and clinics.
-- HIPAA: This table contains PHI. Row-level security (RLS) MUST be enabled.
--        All reads/writes should be captured in an audit log.
--        'reason' and 'notes' fields are particularly sensitive free-text PHI.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS appointments (
    -- Primary key: UUID v4 generated by PostgreSQL to prevent enumeration attacks
    id                      UUID            PRIMARY KEY DEFAULT gen_random_uuid(),

    -- -------------------------------------------------------------------------
    -- Multi-tenant isolation: every appointment is scoped to exactly one clinic.
    -- NEVER query this table without a clinic_id predicate in application layer.
    -- -------------------------------------------------------------------------
    clinic_id               UUID            NOT NULL
                                            REFERENCES clinics(id)
                                                ON DELETE RESTRICT  -- Prevent orphan appointments if clinic deleted
                                                ON UPDATE CASCADE,

    -- -------------------------------------------------------------------------
    -- Core relationships
    -- ON DELETE RESTRICT: Deleting a patient/doctor with future appointments
    --                     must be blocked at DB level; use soft-delete instead.
    -- -------------------------------------------------------------------------
    patient_id              UUID            NOT NULL
                                            REFERENCES patients(id)
                                                ON DELETE RESTRICT
                                                ON UPDATE CASCADE,

    doctor_id               UUID            NOT NULL
                                            REFERENCES doctors(id)
                                                ON DELETE RESTRICT
                                                ON UPDATE CASCADE,

    -- -------------------------------------------------------------------------
    -- Scheduling fields
    -- scheduled_at: stored in UTC; convert to clinic timezone (clinic_settings)
    --               at the application layer for display purposes.
    -- duration_minutes: defaults to clinic_settings.appointment_duration_minutes
    --                   but can be overridden per appointment (e.g., procedures).
    -- -------------------------------------------------------------------------
    scheduled_at            TIMESTAMPTZ     NOT NULL,
    duration_minutes        SMALLINT        NOT NULL
                                            DEFAULT 30
                                            CONSTRAINT chk_duration_positive
                                                CHECK (duration_minutes > 0)
                                            CONSTRAINT chk_duration_max
                                                CHECK (duration_minutes <= 480), -- Max 8-hour appointment

    -- -------------------------------------------------------------------------
    -- Classification fields
    -- -------------------------------------------------------------------------
    status                  appointment_status  NOT NULL DEFAULT 'scheduled',
    type                    appointment_type    NOT NULL DEFAULT 'in_person',

    -- -------------------------------------------------------------------------
    -- Clinical context fields — HIGH SENSITIVITY PHI
    -- HIPAA: 'reason' and 'notes' must be encrypted at rest at the storage layer.
    --        Do NOT log these fields in application logs or error traces.
    --        Access to these columns should require elevated role permissions.
    -- reason: Chief complaint or purpose of visit (e.g., "chest pain follow-up")
    -- notes:  Additional administrative or pre-visit clinical notes
    -- -------------------------------------------------------------------------
    reason                  TEXT            NULL        -- PHI: Chief complaint / visit purpose
                                            CONSTRAINT chk_reason_length
                                                CHECK (char_length(reason) <= 1000),

    notes                   TEXT            NULL        -- PHI: Additional clinical/admin notes
                                            CONSTRAINT chk_notes_length
                                                CHECK (char_length(notes) <= 5000),

    -- -------------------------------------------------------------------------
    -- Audit trail: who created this appointment
    -- created_by references users table (receptionist, doctor, or patient portal)
    -- -------------------------------------------------------------------------
    created_by              UUID            NOT NULL
                                            REFERENCES users(id)
                                                ON DELETE RESTRICT
                                                ON UPDATE CASCADE,

    -- -------------------------------------------------------------------------
    -- Soft-delete: appointments are NEVER hard-deleted for audit/billing trail.
    -- HIPAA: Medical scheduling records must be retained per state law (commonly
    --        6–10 years). Hard deletes are prohibited on PHI records.
    -- -------------------------------------------------------------------------
    deleted_at              TIMESTAMPTZ     NULL,       -- NULL = active; SET = soft-deleted

    -- -------------------------------------------------------------------------
    -- Standard audit timestamps
    -- -------------------------------------------------------------------------
    created_at              TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    -- -------------------------------------------------------------------------
    -- Business rule constraints
    -- -------------------------------------------------------------------------

    -- Prevent double-booking same doctor at same time within a clinic
    -- Note: Full overlap detection requires application-layer logic or a partial
    --       exclusion constraint using tstzrange (see index below).
    CONSTRAINT uq_doctor_scheduled_at
        UNIQUE (doctor_id, scheduled_at, deleted_at), -- deleted_at included so cancelled slots can be reused

    -- Ensure scheduled_at is not in the past on INSERT (advisory; enforced by app too)
    -- Intentionally NOT added here — migrations run in batch and past dates are valid
    -- for historical data imports. Enforce in application layer instead.

    -- Telehealth compliance marker (extensible via future columns)
    CONSTRAINT chk_valid_status_type_combination
        CHECK (
            -- No business rule violations: all combinations valid at DB level
            -- Application layer enforces telehealth-specific rules (consent, platform)
            status IS NOT NULL AND type IS NOT